#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# install-cannbot-trae.sh
#
# One-shot installer that wires CANNBOT into the Trae IDE on macOS / Linux.
#
# What it does:
#   1. Downloads (or copies from a local clone) cannbot-proxy.py to
#      ~/.cannbot/proxy/cannbot-proxy.py
#   2. Asks for your Virtual Key (or reads $CANNBOT_VK) and writes it to
#      ~/.cannbot/vk with mode 0600.
#   3. Installs a small launcher script ~/.cannbot/proxy/run.sh.
#   4. On macOS: writes a per-user launchd plist so the proxy starts on
#      login and restarts if it dies.
#      On Linux: writes a systemd user unit and reloads it.
#   5. Starts the proxy and prints a Trae-ready configuration summary.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/BadFatCat0919/opencannbot/main/install-cannbot-trae.sh | bash
#   # or, from a local clone:
#   ./install-cannbot-trae.sh
#
# Environment overrides:
#   CANNBOT_VK            Pre-fill the Virtual Key (skips the prompt).
#   CANNBOT_PROXY_PORT    Port to listen on (default 8765).
#   CANNBOT_PROXY_HOST    Bind address (default 127.0.0.1).
#   CANNBOT_REPO_RAW      Override the raw-content base URL (for forks).
# ----------------------------------------------------------------------------
set -euo pipefail

REPO_RAW="${CANNBOT_REPO_RAW:-https://raw.githubusercontent.com/BadFatCat0919/opencannbot/main}"
PROXY_URL="$REPO_RAW/cannbot-proxy.py"

INSTALL_DIR="${CANNBOT_INSTALL_DIR:-$HOME/.cannbot/proxy}"
PROXY_FILE="$INSTALL_DIR/cannbot-proxy.py"
RUN_SCRIPT="$INSTALL_DIR/run.sh"
VK_FILE="$HOME/.cannbot/vk"
LOG_FILE="$INSTALL_DIR/proxy.log"
PID_FILE="$INSTALL_DIR/proxy.pid"
PORT="${CANNBOT_PROXY_PORT:-8765}"
HOST="${CANNBOT_PROXY_HOST:-127.0.0.1}"

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*"; }

bold "======================================="
bold "  CANNBOT Proxy for Trae IDE"
bold "======================================="
echo

# ── Sanity checks ──────────────────────────────────────────────────────
command -v python3 >/dev/null 2>&1 || { red "python3 not found. Please install Python 3.8+."; exit 1; }
PY_MAJOR=$(python3 -c 'import sys; print(sys.version_info.major)')
PY_MINOR=$(python3 -c 'import sys; print(sys.version_info.minor)')
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 8 ]; }; then
  red "Python $PY_MAJOR.$PY_MINOR found, need 3.8+."; exit 1
fi

mkdir -p "$INSTALL_DIR" "$(dirname "$VK_FILE")"

# ── 1. Obtain cannbot-proxy.py ─────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
if [ -f "$SCRIPT_DIR/cannbot-proxy.py" ]; then
  cp "$SCRIPT_DIR/cannbot-proxy.py" "$PROXY_FILE"
  green "[1/5] Proxy script copied from local clone -> $PROXY_FILE"
else
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$PROXY_URL" -o "$PROXY_FILE"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$PROXY_FILE" "$PROXY_URL"
  else
    red "Neither curl nor wget found."; exit 1
  fi
  green "[1/5] Proxy script downloaded -> $PROXY_FILE"
fi
chmod +x "$PROXY_FILE"

# ── 2. Configure VK ───────────────────────────────────────────────────
if [ -n "${CANNBOT_VK:-}" ]; then
  VK="$CANNBOT_VK"
elif [ -s "$VK_FILE" ]; then
  VK="$(cat "$VK_FILE")"
  yellow "[2/5] Reusing existing VK from $VK_FILE"
else
  printf "Enter your CANNBOT Virtual Key (vk-...): "
  read -r VK < /dev/tty || VK=""
fi
if [ -z "${VK:-}" ]; then
  red "No Virtual Key provided. Set CANNBOT_VK and re-run, or pass it interactively."
  exit 1
fi
printf '%s\n' "$VK" > "$VK_FILE"
chmod 600 "$VK_FILE"
green "[2/5] Virtual Key saved -> $VK_FILE (mode 0600)"

# ── 3. Write the launcher ─────────────────────────────────────────────
cat > "$RUN_SCRIPT" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-cannbot-trae.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
set -e
export CANNBOT_VK="\$(cat "$VK_FILE")"
export CANNBOT_PROXY_PORT="$PORT"
export CANNBOT_PROXY_HOST="$HOST"
exec "$PROXY_FILE" \\
    --vk "\$CANNBOT_VK" \\
    --port "\$CANNBOT_PROXY_PORT" \\
    --host "\$CANNBOT_PROXY_HOST" \\
    --log "$LOG_FILE"
EOF
chmod +x "$RUN_SCRIPT"
green "[3/5] Launcher written -> $RUN_SCRIPT"

# ── 4. Install service unit ───────────────────────────────────────────
SERVICE_NAME="com.cannbot.proxy"
if [ "$(uname -s)" = "Darwin" ]; then
  PLIST="$HOME/Library/LaunchAgents/$SERVICE_NAME.plist"
  mkdir -p "$(dirname "$PLIST")"
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>$SERVICE_NAME</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$RUN_SCRIPT</string>
    </array>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>StandardOutPath</key><string>$LOG_FILE</string>
    <key>StandardErrorPath</key><string>$LOG_FILE</string>
    <key>WorkingDirectory</key><string>$INSTALL_DIR</string>
</dict>
</plist>
EOF
  launchctl unload "$PLIST" 2>/dev/null || true
  launchctl load -w "$PLIST"
  green "[4/5] launchd agent installed -> $PLIST"
else
  UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  mkdir -p "$UNIT_DIR"
  UNIT="$UNIT_DIR/cannbot-proxy.service"
  cat > "$UNIT" <<EOF
[Unit]
Description=CANNBOT Gateway Proxy for Trae IDE
After=network-online.target

[Service]
Type=simple
ExecStart=$RUN_SCRIPT
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now cannbot-proxy.service
  green "[4/5] systemd user unit installed -> $UNIT"
fi

# ── 5. Verify and print Trae config ───────────────────────────────────
# Give the service a moment to bind.
for _ in 1 2 3 4 5 6 7 8 9 10; do
  if curl -fsS "http://${HOST}:${PORT}/_health" >/dev/null 2>&1; then break; fi
  sleep 0.5
done

HEALTH="$(curl -fsS "http://${HOST}:${PORT}/_health" 2>/dev/null || echo '{"status":"starting"}')"
green "[5/5] Proxy health: $HEALTH"
echo
bold "Done! Configure Trae as follows:"
echo
echo "  API Base URL : http://${HOST}:${PORT}/v1"
echo "  API Key      : ${VK}"
echo "  Model        : (any CANNBOT model, e.g. claude-opus-4-8, glm-5.2, qwen3.7-max)"
echo
echo "Logs   : tail -f $LOG_FILE"
echo "Stop   : launchctl unload ~/Library/LaunchAgents/$SERVICE_NAME.plist   # macOS"
echo "       : systemctl --user stop cannbot-proxy.service                   # Linux"
echo "Remove : $SCRIPT_DIR/uninstall-cannbot-trae.sh"
