<#
.SYNOPSIS
  Install the CANNBOT gateway proxy for Trae IDE on Windows.
.DESCRIPTION
  Same behaviour as install-cannbot-trae.sh: drops the proxy into
  $HOME\.cannbot\proxy, writes the VK to $HOME\.cannbot\vk, and installs
  a per-user scheduled task that starts the proxy on login and restarts
  it on failure.
#>
$ErrorActionPreference = 'Stop'
try { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 } catch {}

$RepoRaw   = if ($env:CANNBOT_REPO_RAW) { $env:CANNBOT_REPO_RAW } else { 'https://raw.githubusercontent.com/BadFatCat0919/opencannbot/main' }
$ProxyUrl  = "$RepoRaw/cannbot-proxy.py"

$InstallDir = if ($env:CANNBOT_INSTALL_DIR) { $env:CANNBOT_INSTALL_DIR } else { Join-Path $env:USERPROFILE '.cannbot\proxy' }
$ProxyFile  = Join-Path $InstallDir 'cannbot-proxy.py'
$RunScript  = Join-Path $InstallDir 'run.cmd'
$VkFile     = Join-Path $env:USERPROFILE '.cannbot\vk'
$LogFile    = Join-Path $InstallDir 'proxy.log'
$Port       = if ($env:CANNBOT_PROXY_PORT) { [int]$env:CANNBOT_PROXY_PORT } else { 8765 }
$Host_      = if ($env:CANNBOT_PROXY_HOST) { $env:CANNBOT_PROXY_HOST } else { '127.0.0.1' }
$TaskName   = 'CANNBOTProxyForTrae'

function Write-Bold($t)  { Write-Host $t -ForegroundColor White }
function Write-Green($t) { Write-Host $t -ForegroundColor Green }
function Write-Red($t)   { Write-Host $t -ForegroundColor Red }

Write-Bold "======================================="
Write-Bold "  CANNBOT Proxy for Trae IDE (Windows)"
Write-Bold "======================================="
Write-Host ""

if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
  Write-Red "python not found in PATH. Please install Python 3.8+ from https://python.org."
  return
}

New-Item -ItemType Directory -Force -Path $InstallDir, (Split-Path $VkFile) | Out-Null

# 1. Download / copy proxy
$LocalProxy = if ($PSScriptRoot) { Join-Path $PSScriptRoot 'cannbot-proxy.py' } else { $null }
if ($LocalProxy -and (Test-Path $LocalProxy)) {
  Copy-Item $LocalProxy $ProxyFile -Force
  Write-Green "[1/4] Proxy copied from local clone -> $ProxyFile"
} else {
  Invoke-WebRequest -Uri $ProxyUrl -OutFile $ProxyFile -UseBasicParsing
  Write-Green "[1/4] Proxy downloaded -> $ProxyFile"
}

# 2. VK
if ($env:CANNBOT_VK) {
  $Vk = $env:CANNBOT_VK
} elseif (Test-Path $VkFile) {
  $Vk = (Get-Content $VkFile -Raw).Trim()
  Write-Host ("[2/4] Reusing existing VK from " + $VkFile) -ForegroundColor Yellow
} else {
  $Vk = Read-Host "Enter your CANNBOT Virtual Key (vk-...)"
}
if (-not $Vk) { Write-Red "No VK provided."; return }
Set-Content -Path $VkFile -Value $Vk -Encoding UTF8
Write-Green "[2/4] Virtual Key saved -> $VkFile"

# 3. Launcher
@"
@echo off
rem Auto-generated by install-cannbot-trae.ps1
set CANNBOT_VK=
for /f "usebackq delims=" %%i in ("$VkFile") do set CANNBOT_VK=%%i
set CANNBOT_PROXY_PORT=$Port
set CANNBOT_PROXY_HOST=$Host_
python "$ProxyFile" --vk %CANNBOT_VK% --port %CANNBOT_PROXY_PORT% --host %CANNBOT_PROXY_HOST% --log "$LogFile"
"@ | Set-Content -Path $RunScript -Encoding ASCII
Write-Green "[3/4] Launcher written -> $RunScript"

# 4. Scheduled task (run at logon, restart on failure)
$action  = New-ScheduledTaskAction -Execute $RunScript -WorkingDirectory $InstallDir
$trigger = New-ScheduledTaskTrigger -AtLogOn
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Highest -LogonType Interactive
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1)
try { Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue } catch {}
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
Write-Green "[4/4] Scheduled task '$TaskName' registered (runs on logon, auto-restart)"

Start-ScheduledTask -TaskName $TaskName | Out-Null
Start-Sleep -Seconds 2

Write-Host ""
Write-Bold "Done! Configure Trae as follows:"
Write-Host ""
Write-Host "  API Base URL : http://$($Host_):$Port/v1"
Write-Host "  API Key      : $Vk"
Write-Host "  Model        : (any CANNBOT model, e.g. claude-opus-4-8, glm-5.2, qwen3.7-max)"
Write-Host ""
Write-Host "Logs  : Get-Content '$LogFile' -Wait"
Write-Host "Stop  : Unregister-ScheduledTask -TaskName $TaskName"
